nksaraf/vinxi

README.md
=> fixed: spelling

packages/vinxi/lib/build.js
=> order handlers by base length desc

.github/workflows/test.yml, packages/vinxi-devtools/dist/mount.js, packages/vinxi/lib/dev-server.js, packages/vinxi/package.json, pnpm-lock.yaml, test/hmr.test.ts, test/package.json, test/playwright.config.ts
I couldn't run the tests, but found it worked after updating playwright, and then adding an `await` to the hmr test to have cheerio complete element selection before moving on as it prev. failed with this:
```sh
Error: expect(received).toBe(expected) // Object.is equality
Expected: "<h1 data-test-id=\"content\">Hello from Vinxi</h1>"
Received: "<h1 data-test-id=\"content\">Hello from Vinxi too</h1>"
```
=> working tests

.changeset/four-ladybugs-build.md, packages/vinxi/lib/build.js, pnpm-lock.yaml
Still not clear what they are doing but commenting them out seems to fix my pre-render issues.
=> Fix Pre-render by removing Build Aliases

packages/vinxi/lib/manifest/dev-server-manifest.js
- builds on top of `https://github.com/nksaraf/vinxi/pull/31` to also support `handler` (`transform` is deprecated in favor of `handler`)
- properly orders indexhtmlTransforms for plugins that specify `"pre"` or `"post"` order
vite documentation: https://vitejs.dev/guide/api-plugin#transformindexhtml
=> Respect plugins indexHtmlTransform ordering

.changeset/beige-colts-design.md, packages/vinxi/bin/cli.mjs
=> windows: use file url to import server in start command

.changeset/four-terms-bathe.md, .github/workflows/autofix.yml, examples/solid/ssr/basic/app/Counter.module.css, examples/solid/ssr/basic/app/Counter.tsx, packages/vinxi/lib/manifest/collect-styles.js, packages/vinxi/lib/manifest/dev-server-manifest.js, packages/vinxi/lib/plugins/css.js
=> (feat): css modules support

.changeset/tough-maps-tap.md, packages/vinxi-directives/package.json, packages/vinxi-directives/parse.js, packages/vinxi/bin/cli.mjs, packages/vinxi/lib/fs-router.js, packages/vinxi/lib/load-app.js
=> (perf): avoid jiti if loading a js/mjs/cjs file

.changeset/beige-plums-poke.md, packages/vinxi/lib/load-app.js
- Remove duplicated logic node/bun
- Add timestamp on import for cache busting
Todo
closes #94
=> fix: config changes not applied on server restart

docs/app/components/Navigation.jsx
=> docs: Fix sidebar active marker position

.changeset/thin-windows-glow.md, packages/vinxi-directives/plugins/shim-exports.js, packages/vinxi-directives/transform.test.js
fixes #129 & https://github.com/solidjs/solid-start/issues/1261
=> Add onModuleFound callback to shimExportsPlugin

.changeset/angry-rivers-wash.md, packages/vinxi/bin/cli.mjs, packages/vinxi/lib/build.js
- feat: add vinxi serve command (static file server), options --dir, --host, --port, --base
- fix: app.server.baseURL support for SPA builds
=> fix: app.server.baseURL support for SPA builds

docs/app/pages/cli.md
=> Update cli.md - vinxi serve

.changeset/brave-forks-judge.md, packages/vinxi/runtime/server-types.d.ts, packages/vinxi/runtime/server.js, packages/vinxi/runtime/server.test.ts, test/async-context.test.ts
=> fix: server helpers not accepting h3Event symbol

.changeset/twenty-bags-check.md, packages/vinxi-doc/doc.js, packages/vinxi-doc/package.json, packages/vinxi-doc/tsconfig.json, packages/vinxi-doc/types.d.ts
=> fix: @vinxi/doc types

docs/.vitepress/config.mts
the link pointed to vitepress instead of vinxi repo
=> Fix github link

docs/api/cli.md
=> Vinxi version docs

.changeset/spicy-dogs-dance.md, packages/vinxi/lib/load-app.js
=> fix: fix .ts config file extensions in load-app.js

docs/api/cli.md
I finally figured out how to wire everything up (solid-router, server.baseURL, vinxi serve). Thank you for all the help so far.
=> Add to the `vinxi serve` docs

.changeset/seven-glasses-stare.md, packages/vinxi/lib/manifest/collect-styles.js
=> feat: don't crawl for styles in node_modules

packages/vinxi/types/party.d.ts
Hey hey,
Just a little PR here to use the correct type instead of the `connection` type. I was trusting typescript to realize at the end that `Connection` wasn't really what I expected!
=> fix(types): Use the correct type for the party handler callbacks

.github/workflows/autofix.yml, .github/workflows/test.yml, .github/workflows/version.yml
=> ci: upgrade pnpm/action-setup to v4

packages/vinxi/lib/build.js
=> chore: fix typo

.changeset/old-tables-bake.md, packages/vinxi/lib/manifest/prod-server-manifest.js, packages/vinxi/lib/manifest/spa-manifest.js
A quick, self-explanatory, follow up fix regarding #293 😅.
=> fix: replace fetchpriority with fetchPriority

.changeset/sour-suits-fail.md, packages/vinxi/lib/manifest/collect-styles.js
=> fix missing null check on css exclusion

.github/workflows/cr.yml
This will add preview releases to vinxi commits and pull requests! We'd have to install the [app](https://github.com/apps/pkg-pr-new) on this repo as the next step.
Thank you so much for the opportunity!
=> feat: continuous releases with pkg.pr.new

.changeset/cool-laws-exercise.md, packages/vinxi-devtools/package.json, packages/vinxi-directives/package.json, packages/vinxi-doc/package.json, packages/vinxi-openapi/package.json, packages/vinxi-react-server/package.json, packages/vinxi-react/package.json, packages/vinxi-server-components/package.json, packages/vinxi-server-functions/package.json, packages/vinxi-solid/package.json, packages/vinxi/package.json
Make licenses more explicit for automated license checks.
=> add "license" field to library package.json files

docs/api/server/session.md
Fixes some layout/formatting issues on the API's > Server API > Session page
=> Fixed session content formatting

.github/workflows/test.yml
Expand test CI to node 20+22
Before: 18
After: 18, 20, 22
Closes https://github.com/nksaraf/vinxi/issues/413
- https://github.com/nksaraf/vinxi/issues/413
=> Expand node test matrix with node 20+22

.github/workflows/autofix.yml, .github/workflows/cr.yml, .github/workflows/test.yml, .github/workflows/version.yml
unbuntu-latest has changed from ubuntu 22 to 24, and it breaks CI
this pin the ubuntu-22.04
=> pin CI to ubuntu-22.04

.changeset/light-panthers-bow.md, packages/vinxi/lib/dev-server.js, packages/vinxi/lib/router-mode.d.ts, packages/vinxi/lib/router-modes.js
fixes #394
adapted from #404 to operate on a per router basis
=> feat: allow custom HMR configuration on a per router basis
