nksaraf/vinxi

packages/vinxi-server-functions/client.js
Running `example-bare` from solid-start on Windows fails to resolve `references-runtime.js`.
```cmd
[plugin:vite:import-analysis] Failed to resolve import "C:UsersDavideDesktopsolid-start
ode_modules.pnpm@vinxi+plugin-server-functions@0.0.32_vinxi@0.0.40
ode_modules@vinxiplugin-server-functions
eferences-runtime.js" from "src\entry-client.tsx". Does the file exist?
C:/Users/Davide/Desktop/solid-start/examples/bare/src/entry-client.tsx:1:38
1  |  import { createComponent as _$createComponent } from "solid-js/web";
2  |  import { createServerReference } from 'C:\Users\Davide\Desktop\solid-start\node_modules\.pnpm\@vinxi+plugin-server-functions@0.0.32_vinxi@0.0.40\node_modules\@vinxi\plugin-server-functions\references-runtime.js';
|                                         ^
3  |  import { …
```
=> Windows: not resolving references-runtime.js from server-functions package

packages/vinxi/lib/build.js
This PR adds support for nitro prerendering during the build.
Standard order ref from nitro CLI: https://github.com/unjs/nitro/blob/main/src/cli/commands/build.ts#L36 (after copying public assets to make them accessible but if for some reason you might want to move it before it works)
=> feat(build): support prerendering

.changeset/old-eggs-travel.md, packages/vinxi/lib/manifest/prod-server-manifest.js
This PR expands the assets returned from the manifest to include JS files.
The approach I took here was to map them to `<link>` elements with `rel="modulepreload"`. I hope this fits with what is intended. I needed to do extra filtering in start to handle lazyRoutes properly and inject them in the head the way I wanted to but I think in general we need to expose these assets.
=> Enable JS Link Preload

packages/vinxi/lib/manifest/collect-styles.js
This Pull Request is fixing the node resolution inside collect-styles.js, as it currently gives error messages for transformed imports in certain cases, so it can fix https://github.com/nksaraf/vinxi/issues/26.
=> Fix manifest plugin, collect-styles.js node resolution

packages/vinxi/lib/dev-server.js
When the dev server restarts because of config changes vite dev server are not closed keeping i.e. hmr websocket server running and ports occupied.
Now when the dev server is closed all vite dev server are also closed.
=> close vite dev server

.changeset/bright-baboons-sing.md, packages/vinxi/lib/fs-router.js, packages/vinxi/lib/plugins/fs-watcher.js
- Be on Windows
- Run `pnpm -F example-hackernews run dev` in `solid start`
- Edit `[...stories].tsx`
Something to do with server functions I think but in any case it's probably a good idea to normalize the paths received from the fs watcher.
Edit: Moved the normalization to the fs-router in case other code modifies the routes in the future. 
```
14:09:40 [vite] hmr update /@id/C:/Users/Davide/Desktop/solid-start/examples/hackernews/src/routes/[...stories].tsx?pick=default&pick=$css
14:09:40 [vite] page reload src/routes/[...stories].tsx
outes[...stories].tsx?pick=route (resolved id: C:UsersDavideDesktopsolid-startexampleshackernewssroutes[...stories].tsx?pick=route) in C:/Users/Davide/Desktop/solid-start/node_modules/.pnpm/vinxi@0.0.54_@types+node@20.10.1_debug@4.3.4_rollup@3.28.1/node_mo …
```
=> normalize paths from fs watcher

.changeset/early-pumas-pump.md, .changeset/shy-comics-crash.md, examples/react/rsc/spa/app/client.tsx, examples/solid/ssr/basic/app/app.tsx, packages/vinxi-server-functions/client-runtime.js, packages/vinxi-server-functions/server-runtime.js, packages/vinxi/lib/app.js, packages/vinxi/lib/build.js, packages/vinxi/lib/dev-server.js, packages/vinxi/lib/manifest/dev-server-manifest.js, packages/vinxi/lib/manifest/prod-server-manifest.js, packages/vinxi/lib/nitro-dev.js, packages/vinxi/lib/plugins/config.js, packages/vinxi/lib/plugins/manifest.js, packages/vinxi/lib/vite-dev.d.ts
fixes [Bug?]: Router "base" property is flaky solidjs/solid-start#1158 #55
=> (feat): deep support for `server.baseURL` API from nitro in dev & prod,

.changeset/swift-files-film.md, packages/vinxi/lib/nitro-dev.js, pnpm-lock.yaml
=> (feat): support devProxy nitro options, in vinxi dev server

.changeset/old-squids-fetch.md, packages/vinxi/bin/cli.mjs
Ported over more commands present in solid-start beta 1.
I haven't yet implemented opening in browser.
There's this [extract](https://github.com/withastro/astro/blob/main/packages/astro/src/cli/docs/open.ts) from the Astro CLI, which we also use in the solid CLI. Would this be ok to include in Vinxi to add this functionality?
=> Add additional CLI commands

pnpm-workspace.yaml, test/helpers/create-fixture.ts
This fixes two things.
pnpm scanning `test/.fixtures` and complaining about too many symbolic links.
Adding `!**/.fixtures/**` to pnpm-workspace did not work so I added `/test` and `/test/templates/**` instead.
`proc.kill()` not terminating process. To work around this scripts are now started with node.
Either there is a bug in npm or something is wrong here.
=> fix tests leaving behind processes

.changeset/three-trainers-fetch.md, packages/vinxi/lib/manifest/prod-server-manifest.js
Solid-Start docs build would not load css.
We have to pass a `/` to `joinURL` when no baseURL is defined otherwise we end up with relative paths even if router.base is `/`.
The first arg of `joinURL` is the base.
https://github.com/unjs/ufo/blob/8638f512e3cd982699c9ccc6a3d8f6f010f4a35a/src/utils.ts#L178-L179
Did not touch the `key` prop as I am not sure about its usage.
=> fix: css asset href is relative

.changeset/sour-mayflies-divide.md, packages/vinxi/bin/cli.mjs, packages/vinxi/lib/build.js
https://github.com/solidjs/solid-start/issues/1208
on build the cli determines the preset without checking the app config.
Oh... just noticed that for dev the preset is also determined in the cli. Should it be moved back to the cli for build?
But then you would have to do it again in `createBuild` to cover this I guess. 🤔 
https://github.com/nksaraf/vinxi/blob/16814e6ec17c3fd4b06110191ce919845caecfa0/packages/vinxi/lib/app.js#L176-L179
=> fix: server preset defined in app config not working

.changeset/violet-brooms-design.md, packages/vinxi/lib/build.js
[Reference](https://github.com/nksaraf/vinxi/pull/21#discussion_r1441475523)
=> replace passthrough with fallthrough

.changeset/famous-shrimps-switch.md, .changeset/spicy-keys-matter.md, packages/vinxi/lib/manifest/vite-manifest.js
Introduce stack-tracing, which doesn't allow code to dig into the same
branches again and again.
It was a problem in case when couple of "ids" in manifest reference each
other.
=> findAssetsInViteManifest: Prevent recursive parsing of same ids

.changeset/red-tips-mate.md, packages/vinxi/runtime/server.js
This is upstreaming the PR https://github.com/solidjs/solid-start/issues/1255 made by @oscartbeaumont.
We detect when the event request body is an ArrayBuffer and use it native in `toWebRequest`. This is required to work on `Deno` and `edge functions`
=> upstreams Fix server functions hanging on edge functions solidjs/solid-start#1255

README.md
The stackblitz link for the react rsc spa wasn't working as the path was missing the last directory.
P.S. I don't know what [fw](https://github.com/nksaraf/vinxi/tree/main/examples/react/rsc/fw) stands for otherwise I could have added a row for that in the README
=> fix: react rsc spa example link

.changeset/fifty-dodos-sort.md, packages/vinxi-react/package.json
- feat: vinxi/http package for all the http server related utilities (vinxi/server reexports)
- Create beige-walls-train.md
- fix: Update package.json to include new types and exports
=> fix: add types to @vinxi/react pacakge.json

.changeset/lovely-files-push.md, packages/vinxi/runtime/http-types.d.ts
When creating a set cookie wrapper to define the cookie options, I had to install cookie-es to have those types.
This PR reexports CookieSerializeOptions from vinxi/server for enabling the usage of it.
=> Reexporting type CookieSerializeOptions

docs/guide/build-your-own-framework.md
Instead of only showing `coming soon`, also have a link to this great post for now: 
Community post on the topic: [Bullding a React Metaframework with Vinxi](https://www.brenelz.com/posts/building-a-react-metaframework-with-vinxi/)
=> Add link to community post on building a framework with vinxi

.changeset/gentle-bulldogs-hide.md, packages/vinxi/package.json, pnpm-lock.yaml
With the nitro 2.9.0 release, it appear that vinxi can do with the stable rather than the nightly.
=> Move to stable nitro releases

.changeset/two-chairs-admire.md, packages/vinxi-router/api-handler.js
This adds the `params` object to the H3 `event` for the API router instead of passing it as a separate object.
Closes #242
=> feat: add params to h3 event object for api router

examples/solid/ssr/basic/app/server.tsx
This is imported twice, and breaks the example
`import { getManifest } from "vinxi/manifest"; `
=> fix example: solid/ssr/basic - Duplicate import

.changeset/many-jobs-clean.md, packages/vinxi/lib/dev-server.js
My project loads SVG files from another package in a monorepo, but it doesn't work in vinxi-based Solid Start.
vinxi modified `server.fs.allow` value in Vite config, but it doesn't follow the documentation to use `searchForWorkspaceRoot` method to properly allow monorepo usage: https://vitejs.dev/config/server-options.html#server-fs-allow
=> fix: allow serving resource files from monorepo in dev server

.changeset/eleven-news-hear.md, packages/vinxi/lib/app.js, packages/vinxi/lib/dev-server.js
Fix: #280 
Including small correction. Listhen's https option is optional and defaulting to undefined works out for vite as well.
=> fix: https type def

.changeset/silly-walls-notice.md, packages/vinxi/lib/plugins/css.js
There is an issue with hmr not working as expected for css modules.
https://github.com/solidjs/solid-start/issues/1400
Edit the css module and the styling on the counter button will disappear.
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/solidjs-solid-start-zd3fz8?file=src%2Fcomponents%2FCounter.module.css) 
This Vite plugin sends custom hmr events to update inlined css. When updating a css module the generated classes change and don't match anymore with already rendered components. 
https://github.com/nksaraf/vinxi/blob/4bddafe1b7e873ef691392ebaf7ea4f4875e39d4/packages/vinxi/lib/plugins/css.js#L22-L30
Currently I see two ways to handle css modules.
- [In PR] Don't do full custom event handling. Allowing vite to send …
=> fix: css module hmr update

.changeset/tender-spiders-bake.md, packages/vinxi/package.json, pnpm-lock.yaml
Align direct esbuild dependency version with transitive esbuild dependency from vite and nitropack.
When creating a solid-start app, both esbuild 0.18 and esbuild 0.20 are installed.  This happens because the vite dependency in vinxi allows Vite 5.2.x which pulls in esbuild 0.20, but vinxi depends on esbuild 0.18.
Since vinxi uses esbuild directly just to process its own config, I thought it should be safe to update to esbuild 0.20, saving some download time and perplexity. I've also updated the Vite version range to make the result more consistent between installs with and without an existing package lock file. 
Esbuild release notes: https://github.com/evanw/esbuild/releases
=> chore(vinxi): ensure installing vinxi only install one esbuild version

.changeset/smart-horses-film.md, packages/vinxi/lib/manifest/prod-server-manifest.js, packages/vinxi/lib/manifest/spa-manifest.js
`precendence` isn't valid html and in React it would be called `precedence` 😅🙈. The html compatible equivalent is `fetchpriority`.
=> fix: replace stylesheet precendence with fetchpriority

.changeset/tiny-items-report.md, packages/vinxi-server-functions/server-handler.js
```ts
const get1 = async () => {
const res = await fetch("http://localhost:3000/_server", {
method: "GET",
headers: {
"Server-Action":
"/Users/or/Desktop/vinxi/examples/solid/ssr/basic/app/getActions.tsx#getAction",
},
});
const data = await res.json();
console.log(data);
};
```
this is now valid, i was also trying to make this valid:
```ts
const get2 = async () => {
const res = await fetch(
`http://localhost:3000/_server?serveract=${encodeURIComponent(
"/Users/or/Desktop/vinxi/examples/solid/ssr/basic/app/getActions.tsx#getAction",
)}`,
{
method: "GET",
},
);
const data = await res.json();
console.log(data);
};
```
but the codebase was so messy and untyped i barely could have got anything moving. this is useful for an open graph library we are building as a part of solid mediakit.
i'm …
=> server functions: allow get requests

.changeset/spicy-apples-protect.md, packages/vinxi/package.json
Solid Start imports `CustomizableConfig` from `vinxi/dist/types/lib/vite-dev`. With `moduleResolution: "node"` this works fine, but `moduleResolution: "bundler"` (which is now recommended) requires all subpath exports to be listed in `exports` and (for posterity) `typesVersions`, so I've added wildcard entries for `./dist/types/*`.
This will fix the Vite part of https://github.com/solidjs/solid-start/issues/1505
=> Add ./dist/types exports to package.json

packages/vinxi/package.json
Export the `lib/vite-dev` type to facilitate users to import the types defined in it.
For example, to provide convenience for defining user-configured types in the solid-start project.
https://github.com/solidjs/solid-start/blob/914647c9d122cfb3dd974d904012a8eb38898322/packages/start/config/index.d.ts#L2
=> feat: export `lib/vite-dev` for external use

packages/vinxi/lib/manifest/collect-styles.js
This makes Vinxi stop collecting styles from dynamic dependencies, which triggers Vite transforms per each dependency and drops dev performance significantly if done on modules that contain a lot of dynamic dependencies, potentially because of using `import.meta.glob()`.
=> Fix style collection to not collect from dynamic deps

.changeset/giant-dolphins-exist.md, packages/vinxi/lib/manifest/collect-styles.js
This fixes the following bug: https://github.com/solidjs/solid-start/issues/1478
I understand that it was an attempt to avoid FOUC, but it should be done better, because resulting style order is wrong. Also it eliminates duplication of styles in dev mode.
=> Fix style order in dev mode

.changeset/metal-elephants-worry.md, packages/vinxi/lib/plugins/css.js
Vinxis custom hot css update suppresses updates of css files imported with `?url`.
Css files imported with `?url` should be hot updated properly. 
The suppression of vite hot css updates (by returning `[]`) already had to be disabled for css modules, so I thought why not just remove the suppression at all... Do you know why the vanilla vite hot css updates were disabled by returning `[]` 😅? If they were disabled for some good reason I can search for a different fix 😉.
URL: https://stackblitz.com/edit/github-holpn7?file=src%2Froutes%2Findex.tsx,src%2Froutes%2Findex.css
1. Run `npm run dev`
2. Open `./src/routes/index.css` and change the background-color
3. Result: The css is not hot updated
=> fix: always run vanilla vite hot css updates after vinxis custom updates

.changeset/nervous-pandas-do.md, examples/vanilla/trpc/app.config.js, examples/vanilla/trpc/handler.js, examples/vanilla/trpc/trpc.d.ts, packages/vinxi-react-server/index.js, packages/vinxi-react-server/rsc-handler.tsx, packages/vinxi/lib/build.js, packages/vinxi/lib/path.js, packages/vinxi/lib/router-dev-plugins.js
Node has reserved `#` for [imports](https://nodejs.org/api/packages.html#subpath-imports)
>Entries in the "imports" field must always start with # to ensure they are disambiguated from external package specifiers.
This swaps it to `$`. I tested it by modifying my `node_modules` install of vinxi and my dev server worked again resolving #249.
=> Fixed node imports incompatibility

test/basic.test.ts, test/fs-router.test.ts, test/helpers/create-fixture.ts, test/helpers/playwright-fixture.ts, test/hmr.test.ts, test/playwright.config.ts, test/rsc.test.ts, test/srv-fn.test.ts, test/templates/react-rsc/app/Counter.tsx, test/templates/react-srv-fn/app/App.tsx, test/templates/react-ssr-fs/app/app.tsx, test/templates/react-to-web-request/app/App.tsx, test/templates/react/app/root.tsx, test/to-web-request.test.ts
This PR tries to reduce the flakiness of the tests as much as possible. But it isn't perfect: sometimes the page hydration just fails for unknown reasons, especially on Windows. The new `isReady` check tries to recover from hydration fails, by reloading the page, which seems to work pretty solidly. Longterm though we should think about rewriting a lot of the tests, especially those related to HMR & `fixture.updateFile`.
I ran the updated tests countless times with force-pushes and so far got zero fails with the latest version.
=> [WIP] fix: wait for hydration via react effect

.changeset/five-wasps-love.md, packages/vinxi/lib/build.js
Deployment detection for platforms like Netlify and Vercel were not working because we set a preset even when the user wasn't. I've removed this but kept the Bun clause in. That shouldn't impact the other platforms I think.
=> fix automatic deployment detection by not forcing node preset

packages/vinxi/lib/manifest/collect-styles.js
Continued from #316, cc @katywings
This PR adds `// @vinxi-ignore-style-collection` directive to ignore a module from the style collection.
The directive only works when added at the top of the file, before having any meaningful code beside comments and whitespaces.
=> feat: add comment directive to ignore style collection

.changeset/sharp-kiwis-jump.md, packages/vinxi/lib/manifest/dev-server-manifest.js
Assets order returned by dev-server-manifest is not correct. This causes `vite:react-refresh` preamble script to be inserted after the client runtime. Causing an occasional error.  closes #272
```
Error: @vitejs/plugin-react can't detect preamble. Something is wrong. See https://github.com/vitejs/vite-plugin-react/pull/11#discussion_r430879201
at app.tsx:33:5
```
```js
[  
{
name: 'vite:react-refresh',
enforce: 'pre',
config: [Function: config],
resolveId: [Function: resolveId],
load: [Function: load],
transformIndexHtml: [Function: transformIndexHtml]
},
{
name: 'vinxi:inject-client-runtime',
configResolved: [Function: configResolved],
apply: 'serve',
transformIndexHtml: [Function: transformIndexHtml]
},
]
```
```js
[
{
name: 'vinxi:inject-client-runtime',
configResolved: [Function: …
```
=> fix: vite plugin assets order

docs/.vitepress/config.mts
- Notice that the links to https://vinxi.vercel.app/guide.html and https://vinxi.vercel.app/api.html on the official website are broken.
=> chore: remove broken links

packages/vinxi-mdx/package.json
This makes the package source code much easier to find from the `npm` page!
=> Fix `vinxi-mdx` package description and link

.changeset/polite-llamas-notice.md, packages/vinxi/bin/cli.mjs, packages/vinxi/lib/build.js
- ensures that we don't run out of memory because all the multiple vite builds piling up
- not too many file handles open for one process
- proper cleanup when work gets done
=> run each router build in separate node processes

.changeset/tough-timers-admire.md, packages/vinxi/lib/chunks.js, packages/vinxi/lib/chunks.test.js
This replaces the hashing function with an actual hash algorithm (djb2).
The original code comes from https://github.com/sveltejs/svelte/blob/0203eb319b5d86138236158e3ae6ecf29e26864c/packages/svelte/src/utils.js#L7. 
I also added a Map to avoid duplicate hashing of earlier inputs.
```ts
[
{ value: 'abc', hashNew: '2nhvp3', hashOld: 294 },
{ value: 'cba', hashNew: '2nhu0v', hashOld: 294 },
{
value: '/app/src/server/project.js',
hashNew: '1gxub3t',
hashOld: 2526
},
{
value: '/app/src/project/server.js',
hashNew: '1dkakbx',
hashOld: 2526
}
]
```
Benchmark wise I didn't do a lot. But the few builds I did on a large project look okay:
|        | SSR   | Client | Server-fns |
| ------ | ----- | ------ | ---------- |
| New 1  | 8.93s | 12.84s | 9.40s      |
| New 2  | 8.73s | 13.38s | 9.72s …
=> fix: hash chunks with djb2

.changeset/great-boats-laugh.md, packages/vinxi/bin/cli.mjs, packages/vinxi/lib/app.js, packages/vinxi/lib/build.js, packages/vinxi/lib/dev-server.js, packages/vinxi/lib/load-app.js
This PR adds support for Vite [modes](https://vitejs.dev/guide/env-and-mode#modes)
=> Add support for Vite --mode

.changeset/silent-rockets-live.md, packages/vinxi/runtime/http-types.d.ts, packages/vinxi/runtime/http.js
`useBase` is a useful H3 utility for creating nested routers. Having it available directly from Vinxi would be useful.
https://h3.unjs.io/guide/router#nested-routers
> You can nest routers to create a tree of routers. This is useful to split your application into multiple parts like the API and the website.
> ```js
> websiteRouter.use("/api/**", useBase("/api", apiRouter.handler));
> ```
=> Re-export useBase from H3

.changeset/metal-files-itch.md, packages/vinxi/lib/build.js
Removes the js bundles from the "public/assets" folder for routers that have
- type = 'http'
- target = 'server'
Fixes #363
=> fix(vinxi): remove js assets from router targeting server with type http

docs/guide/route-rules.md
The configuration option requires a "to", which is omitted in the docs.
=> Fix docs syntax for proxy routeRules

.changeset/grumpy-masks-accept.md, docs/api/manifest.md, packages/vinxi/types/manifest.d.ts
I found that `Asset` type is wrong.
As I understood this is always object which has `tag` and `attrs`. When `tag` is `'script' | 'style'`, it also could be `children: string` in it.
So I updated type for this.
=> fix Asset type

.changeset/four-guests-deny.md, packages/vinxi-router/api-handler.js, packages/vinxi-router/api.js, packages/vinxi-router/package.json
The context.params is being overridden here
https://github.com/nksaraf/vinxi/blob/cb790e1ff1d4062b96174935891af6dbccdc50cb/packages/vinxi-router/api-handler.js#L5-L14
=> Update path-to-regexp and don't override the params on the routes handler

packages/vinxi/lib/manifest/collect-styles.js
Because of this fix, https://github.com/vitejs/vite/pull/17922, our way of importing css as js modules with default exports with css text, stopped working.
We are expected to use ?inline query to get the desired format, so this fixes that
=> Update collect-styles.js to use ?inline to get the css during ssr

.github/workflows/autofix.yml, .github/workflows/cr.yml, .github/workflows/test.yml, .github/workflows/version.yml, package.json
This set in root package.json, the:
"packageManager": "pnpm@8.15.9"
Using `corepack enable` it'll automatically set the currently used pnpm version.
I made this PR, because I'm currently juggling a lot of `npm i -g pnpm@8 / 9` between solidjs repos, and this appear to work quite well for automating it.
=> Add corepack, to help adjust pnpm version

packages/vinxi/lib/manifest/collect-styles.js
Importing a css file with `?url` results in
`Error when evaluating SSR module` errors during `vite dev`. The error is caused by Vinxi appending `&inline=true` for the ssrLoadModule calls. Vite `ssrLoadModule` expects urls to only have `?inline`, the user-provided `url` parameter has to be removed.
Detailed error:
```
Error when evaluating SSR module /src/styles.css?url=&inline=true:
|- RollupError: Parse failure: Expression expected
At file: /src/styles.css?url=&inline=true:1:1
```
[vinxi-vite6-css-urls.zip](https://github.com/user-attachments/files/18672267/vinxi-vite6-css-urls.zip)
1. pnpm install && pnpm dev
2. Open `localhost:3000` in the browser
3. The error will be logged in the shell
Branches:
- vite6: vite 6, vinxi 5 - Error occurs
- master: vite 5, vinxi 4 - No error …
=> fix: delete url parameter for ssrLoadModule calls in findStylesInModuleGraph

.changeset/six-schools-ring.md, packages/vinxi/lib/manifest/collect-styles.js
All CSS imported with `?url` and other such sideeffects is rendered on the server during DEV. This is a regression introduced with b6d9643 / 1ac2df3.
CSS imported with sideeffects should not be rendered on the server during DEV. The goal here is to bring vinxi > v0.5 CSS rendering back in line with v0.4.3. This wont fix inconsistencies already existing from the v0.4.3 days (thus the red entries under "SHOULD" in the comparison table 😅).
The new `cssUrlParamsWithoutSideEffects` and
`injectQuery` functions are copied from Remix, opening up further future alignment of the logic.
- Applied patch in a local copy of the `Vinxi 0.5.2 & Vite 6` stackblitz. The results of this are included in the comparison table in the `After fix` columns.
- Applied patch in a real project …
=> fix: exclude css with sideeffects from ssr during dev

.changeset/shy-jokes-learn.md, packages/vinxi/bin/cli.mjs, packages/vinxi/lib/build.js
The mode argument was not being passed to `vite.build()` in `createViteBuild()`
This fixes #378
=> Enable vite `mode` flag

.changeset/weak-students-glow.md, packages/vinxi/bin/cli.mjs, packages/vinxi/lib/build.js
This PR fix #388 and its duplicate #434 .
This was done by adding the `configFile` argument to following embedded builds.
=> fix: use CLI-given config file

packages/vinxi/lib/nitro-dev.js
crossws 0.3.0 renamed ctx to _internal:
https://github.com/unjs/crossws/releases/tag/v0.3.0
This broke vinxi when using this version of crossws and crashes the app.
I didn't see the use of this in nitro-dev, so I removed it. If this still has use, let me know what it is and I'll figure it out.
Thank you!
=> fixed crossws 0.3.0 compatibility

.changeset/fair-eggs-yawn.md, docs/package.json, packages/vinxi/package.json, pnpm-lock.yaml
Bump the nitropack to 2.11.4
I updated vinxi/vitepress in the /docs, to make sure there won't be lockfile conflicts with old versions from /docs package.
https://github.com/nitrojs/nitro/releases
=> Nitro 2.11

.changeset/proud-queens-develop.md, packages/vinxi/lib/vite-dev.d.ts
Removed it from `Omit` as I didn't find any reason to keep it there
fixes #466
=> feat: allow custom `clearScreen` configuration

.changeset/afraid-tigers-chew.md, packages/vinxi/bin/cli.mjs
This ensures the `--mode` CLI arg is ultimately passed to the `vite` dev server. I wasn't quite sure where best do this, and I don't love mutating a property on an object, but this seems to work well.
Fixes https://github.com/nksaraf/vinxi/issues/471
=> fix: ensure --mode flag works for `dev` commad

.changeset/mean-plants-mix.md, packages/vinxi/lib/build.js
added condition for removing files to match
server files leak into client in compressed js|cjs|mjs files 
enhanced the condition to remove files from public directory in build to include compressed js files
=> fix: server code leaked in client bundle in compressed js files.

.changeset/gorgeous-bees-talk.md, packages/vinxi/package.json, pnpm-lock.yaml
now we'll get things like `waitUntil` in `getRequestEvent()?.nativeEvent` in solid and other frameworks
=> fix: nitro H3Event extension
